input_seq: "/your/pathto/read.bam"
input_format: "bam" # Options: "bam", "fastq", "fasta"
anchor_seq:
  - "TATATGGAGTTCCGACGCGT"
  - "GGTACCGTGATGCGGTTTTG"
  - "AGATCGCCGTGTAATCTAGA"
  - "ACTAGTGATACCGAGCGCTG"
output_dir: "/your/pathto/output_dir/"
variant_dict: "/your/pathto/variant_dict.csv"